### ISSUE TITLE
Don't attempt connections on the main thread

### ISSUE THREAD

**Issue by ajayyy** [uorocketry/rocket-ground-station#71]
This is causing the UI to freeze while connection and it freezes for several seconds if the IP is incorrect.

**Comment by Saurabhpatil-dev** [comment]
Hey @ajayyy , Can you please share more details ?

**Comment by ajayyy** [comment]
@Saurabhpatil-dev Hi, it looks like you are not part of uORocketry. This project is not setup well to accept external contributions, but thanks a lot for the offer!
